#!/bin/bash
# 第 22 轮收口（模型通道中断后接续）：
# 大设置页「搬回旧版」之后的**全量回归** —— 顺序跑、不并行（3.6G 内存，一个无头 Chrome 约 180MB）。
cd /home/ubuntu/novel-app || exit 1
say(){ echo; echo "=== $* ==="; }
say "⓪ 同步前端到 apk 资源副本"
python3 tools/sync_pkg.py; echo "sync exit=$?"
say "① 本屏主判据：大设置页回归（13 条）"
node tools/e2e-settings.js; echo "settings exit=$?"
say "①b 反证 nopref（抹掉 [data-pref]）"
SETR_FORCE=nopref node tools/e2e-settings.js; echo "nopref exit=$?"
say "①c 反证 nopass（抹掉改密码入口）"
SETR_FORCE=nopass node tools/e2e-settings.js; echo "nopass exit=$?"
say "①d 反证 notab（抹掉底部导航高亮）"
SETR_FORCE=notab node tools/e2e-settings.js; echo "notab exit=$?"
say "①e 反证 nogroup（删掉一个分区）"
SETR_FORCE=nogroup node tools/e2e-settings.js; echo "nogroup exit=$?"
say "② 回归 · 三态"
node tools/e2e-states.js; echo "states exit=$?"
say "③ 回归 · 不遮挡"
node tools/e2e-cover.js; echo "cover exit=$?"
say "④ 回归 · UI 硬判据（断行/热区/溢出/居中/动效）"
node tools/e2e-uicheck.js; echo "uicheck exit=$?"
say "⑤ 回归 · 安全区 + 手势"
node tools/e2e-safearea.js; echo "safearea exit=$?"
say "⑥ 回归 · 切书小方块（不穿模）"
node tools/e2e-bkmini.js; echo "bkmini exit=$?"
say "⑦ 回归 · 夜间模式"
node tools/e2e-night.js; echo "night exit=$?"
say "⑧ 回归 · 阅读器底部面板 / 独立目录"
node tools/e2e-readerquick.js; echo "rdquick exit=$?"
say "⑨ 设计令牌 + 色卡"
server/venv/bin/python tools/verify_tokens.py; echo "tokens exit=$?"
SWATCH_FORCE=mismatch server/venv/bin/python tools/verify_tokens.py; echo "swatch-rev exit=$?"
say "⑩ 文案体检（去口语化）"
python3 tools/copy_check.py; echo "copy exit=$?"
COPY_FORCE=bad python3 tools/copy_check.py; echo "copy-rev exit=$?"
say "⑪ 死代码"
python3 tools/deadcode_audit.py; echo "deadcode exit=$?"
say "⑫ 体量（对照基线 ×2）"
python3 tools/size_report.py; echo "size exit=$?"
say "⑬ 无头浏览器收尾"
ps -eo args | grep -c "[h]eadless"
node tools/sweep_chrome.js
say "全部跑完"
