#!/bin/bash
# 第 22 轮（前端大改 · 第 3 屏「设置页」）收口：
# ① 本屏主判据 e2e-settings（含四种反证：nochip / novoice / try / shot）
# ② 第 1、2 屏回归（设置页新增 #settings-nav 吸顶条、引入 settings.css，必须复跑确认没打破）
# 顺序跑、不并行（3.6G 内存，一个无头 Chrome 约 180MB）。
cd /home/ubuntu/novel-app || exit 1
say(){ echo; echo "=== $* ==="; }
say "① 本屏主判据：设置页（分区导航 / 预览卡 / 主题色卡 / 音色三态 / 试听 / 关于）"
node tools/e2e-settings.js; echo "settings exit=$?"
say "①b 反证 nochip（抹掉 data-go）"
SET_FORCE=nochip node tools/e2e-settings.js; echo "nochip exit=$?"
say "①c 反证 novoice（音色接口失败）"
SET_FORCE=novoice node tools/e2e-settings.js; echo "novoice exit=$?"
say "①d 反证 try（试听地址指到不存在的地方）"
SET_FORCE=try node tools/e2e-settings.js; echo "try exit=$?"
say "①e 反证 shot（拍照前不滚 → 名字与图对不上）"
SET_FORCE=shot node tools/e2e-settings.js; echo "shot exit=$?"
say "② 回归 · 三态"
node tools/e2e-states.js; echo "states exit=$?"
say "③ 回归 · 不遮挡"
node tools/e2e-cover.js; echo "cover exit=$?"
say "④ 回归 · UI 硬判据"
node tools/e2e-uicheck.js; echo "uicheck exit=$?"
say "⑤ 回归 · 安全区 + 手势"
node tools/e2e-safearea.js; echo "safearea exit=$?"
say "⑥ 回归 · 切书小方块"
node tools/e2e-bkmini.js; echo "bkmini exit=$?"
say "⑦ 回归 · 夜间模式"
node tools/e2e-night.js; echo "night exit=$?"
say "⑧ 回归 · 阅读器底部面板 / 独立目录"
node tools/e2e-readerquick.js; echo "readerquick exit=$?"
say "⑨ 设计令牌 + 色卡"
server/venv/bin/python tools/verify_tokens.py; echo "tokens exit=$?"
SWATCH_FORCE=mismatch server/venv/bin/python tools/verify_tokens.py; echo "swatch-rev exit=$?"
say "⑩ 文案体检（去口语化）"
python3 tools/copy_check.py; echo "copy exit=$?"
COPY_FORCE=bad python3 tools/copy_check.py; echo "copy-rev exit=$?"
say "⑪ 死代码"
python3 tools/deadcode_audit.py; echo "deadcode exit=$?"
say "⑫ 体量（对照基线）"
python3 tools/size_report.py; echo "size exit=$?"
say "⑬ 无头浏览器收尾"
ps -eo args | grep -c "[h]eadless"
node tools/sweep_chrome.js
say "全部跑完"
